# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(355, 198)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QLineEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(30, 20, 291, 31))
        self.text.setObjectName("text")
        self.downBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downBtn.setGeometry(QtCore.QRect(30, 60, 121, 31))
        self.downBtn.setObjectName("downBtn")
        self.dsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dsBtn.setGeometry(QtCore.QRect(180, 60, 141, 31))
        self.dsBtn.setObjectName("dsBtn")
        self.audioCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.audioCheck.setGeometry(QtCore.QRect(120, 110, 91, 31))
        self.audioCheck.setObjectName("audioCheck")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 150, 291, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")

        self.downBtn.clicked.connect(MainWindow.download)
        self.dsBtn.clicked.connect(MainWindow.search)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.downBtn.setText(_translate("MainWindow", "Download"))
        self.dsBtn.setText(_translate("MainWindow", "Search and Download"))
        self.audioCheck.setText(_translate("MainWindow", "Only Audio"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
